config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'articles#index'
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :upvotes, only: [:create, :destroy]
  resources :knowledge, controller: 'articles', as: 'articles' do
    member do
      get 'featured', to: "articles#featured"
    end
  end
  resources :network, controller: 'contacts', as: 'contacts' do
    member do
      get 'ask_intro', to: 'pages#ask_intro'
      post 'ask_intro', to: 'emails#ask_intro'
    end
  end

  get 'onboarding', to: 'pages#onboarding'
  post 'onboarding', to: 'pages#onboarding_change'

  get 'reporting', to: 'pages#send_report'
  post 'reporting', to: 'emails#send_reporting'
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :article, counter_cache: true
  belongs_to :user
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_article, only: [:create]

  def create
    upvote = @article.upvotes.new user: current_user
    authorize upvote
    upvote.save
    respond_to do |format|
      format.html { redirect_to articles_path }
      format.js { render :upvote }
    end
  end

  def destroy
    upvote = Upvote.find(params[:id])
    authorize upvote
    @article = upvote.article
    upvote.destroy
    respond_to do |format|
      format.html { redirect_to articles_path }
      format.js { render :upvote }
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/views/upvotes/_show.html.erb
<% if current_user.voted_for?(article) %>
  <%= link_to upvote_path(current_user.vote_for(article)), remote: true,
    method: :delete, class: 'card-upvote green-credits' do %>
    <span><%= "\u25b2" %></span>
    <span><%= article.upvotes.count %></span>
  <% end %>

<% else %>
  <%= link_to upvotes_path(article_id: article.id), remote: true,
    method: :post, class: 'card-upvote' do %>
    <span><%= "\u25b2" %></span>
    <span><%= article.upvotes.count %></span>
  <% end %>
<% end %>

app/views/upvotes/create.js.erb
$('#upvote-<%= @article.id %>').html('<%= j render 'upvotes/show', article: @article %>');

app/views/upvotes/upvote.js.erb
$('.upvote-<%= @article.id %>').html('<%= j render 'upvotes/show', article: @article %>');