config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'articles#index'
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :upvotes, only: [:create, :destroy]
  resources :knowledge, controller: 'articles', as: 'articles' do
    member do
      get 'featured', to: "articles#featured"
    end
  end
  resources :network, controller: 'contacts', as: 'contacts' do
    member do
      get 'ask_intro', to: 'pages#ask_intro'
      post 'ask_intro', to: 'emails#ask_intro'
    end
  end

  get 'onboarding', to: 'pages#onboarding'
  post 'onboarding', to: 'pages#onboarding_change'

  get 'reporting', to: 'pages#send_report'
  post 'reporting', to: 'emails#send_reporting'
end

app/views/shared/_button_tag.html.erb
<div class="sticky-button-tags-container">
  <div class="add-link-block">
    <%= choose_action_of_button(button) %>
  </div>

  <div class="button-tags-container text-center">
    <p class="text-left"><strong><%= t('.choose') %></strong>
    <% if current_page?(articles_path) %>
      <%= t('.subject') %>
    <% else %>
      <%= t('.subject') %>
    <% end %>
    </p>
    <form class="filters">
      <input type="radio" id="all" value="" name="filter" checked='checked'>
      <label for="all" class="show-all">
        Voir tout
      </label>
      <% Tag.all.each do |tag| %>
        <input type="radio" id="<%= tag.name.downcase %>"
          value=".<%= tag.name.downcase %>" name="filter">
        <label for="<%= tag.name.downcase %>">
          #<%= tag.name %>
        </label>
      <% end %>
    </form>
  </div>

  <%= render 'shared/credits' %>
</div>

app/views/shared/_credits.html.erb
<p class="made-love">
  Fait avec <i class="fa fa-heart red-heart" aria-hidden="true">
    </i> à Bordeaux par <%= link_to "LeWagon",
    'https://www.lewagon.com/', class:'green-credits' %> et <%= link_to "AQUITI",
    'http://aquiti.fr', class:'green-credits' %>.
    Pour en savoir <%= link_to "plus", 'https://medium.com/@fmerian/ci-dessous-lemail-que-nous-avons-envoy%C3%A9-%C3%A0-nos-entrepreneurs-cette-semaine-9ffb5684659e', class:'green-credits' %>.
</p>

app/views/shared/_drift.html.erb
<!-- Start of Async Drift Code -->
<script>
!function() {
  var t;
  if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0,
  t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ],
  t.factory = function(e) {
    return function() {
      var n;
      return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
    };
  }, t.methods.forEach(function(e) {
    t[e] = t.factory(e);
  }), t.load = function(t) {
    var e, n, o, i;
    e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"),
    o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js",
    n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
  });
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('fvupwr8cfu36');
</script>
<!-- End of Async Drift Code -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_google_analytics.html.erb
<% if Rails.env.production? %>
  <%= javascript_tag("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-107088423-1', 'auto');") %>
<% end %>

app/views/shared/_mail_form.html.erb
  <%= form_tag(request.env['PATH_INFO'], method: :post, action: :upload, multipart: true) do %>
    <p><%= t('.from') %> <%= current_user.email %></p>
    <p><%= t('.to') %> florent.merian@aquiti.fr</p>
    <%= file_field_tag 'file', class: "upload-field" %>
    <%= label_tag(:message, "Message:") %>
</div>
    <%= text_area_tag(:message, (render text),escape: true,
      class: "form-control summernote-mail") %>

  <div class="form-model">
  <% if current_page?(reporting_path) %>
    <%= submit_tag t('.your-report'), class: "btn btn-success" %>
  <% else %>
    <%= submit_tag t('.ask-intro'), class: "btn btn-success" %>
  <% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Left Part (logo) -->
  <div id="navbar-wagon-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.svg" %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <!-- Middle Part -->
    <nav id="navbar-wagon-middle">
      <%= link_to_if(current_page?(root_path ) || current_page?(articles_path),
          t('.ressources'), articles_path, html_option = {class:"section active"}) do
        link_to t('.ressources'), articles_path, class:"section" # << else
      end %>
      <%= link_to_if(current_page?(contacts_path), t('.experts'), contacts_path,
        html_option = {class:"section active"}) { link_to t('.experts'), contacts_path,
        class:"section" } %>
    </nav>
  <% end %>

  <!-- Right Part -->
  <% if user_signed_in? %>
    <div id="navbar-wagon-right">

      <!-- Links when logged in -->
        <div>
          <%= button_send_reporting(current_user) %>
          <%= button_new_invitation(current_user) %>
        </div>

    <div class="profile-dropdown">
      <div class="dropdown">
        <%= link_to "\u2026", '#', class: "dropdown-toggle",
          id:"navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_onboarding(current_user) %>
          </li>
          <li>
            <%= link_admin(current_user) %>
          </li>
          <li>
            <%= link_sign_out(current_user) %>
          </li>
        </ul>
      </div>
    </div>

    <% end %>
  </div>

</div>

<% if user_signed_in? %>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-ellipsis-h fa-2x dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to t('.ressources'), articles_path %>
        </li>
        <li>
          <%= link_to t('.experts'), contacts_path %>
        </li>
        <li>
          <%= link_sign_out(current_user) %>
        </li>
      </ul>
    </div>
  </div>
<% end %>