config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'articles#index'
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :upvotes, only: [:create, :destroy]
  resources :knowledge, controller: 'articles', as: 'articles' do
    member do
      get 'featured', to: "articles#featured"
    end
  end
  resources :network, controller: 'contacts', as: 'contacts' do
    member do
      get 'ask_intro', to: 'pages#ask_intro'
      post 'ask_intro', to: 'emails#ask_intro'
    end
  end

  get 'onboarding', to: 'pages#onboarding'
  post 'onboarding', to: 'pages#onboarding_change'

  get 'reporting', to: 'pages#send_report'
  post 'reporting', to: 'emails#send_reporting'
end

app/views/pages/_onboarding_text.html.erb
<div id="onboarding_text_1" class="active">
  <h1><b>Cher(e)s entrepreneur(e)s, ensemble nous démarrons notre collaboration, voici quelques recommandations.</b></h1>
  <h2><b>Bienvenue</b></h2>
  <p>Nous vous remercions pour votre confiance et sommes ravis de participer au développement
      de votre entreprise.</p>
  <p>D'abord, nous souhaitons rapidement nous présenter pour comprendre qui nous sommes,
      ce que nous faisons et la manière dont nous travaillons.</p>
  <h2><b>Notre métier</b></h2>
  <p>En bref, nous investissons tous les mois dans 2 à 3 entreprises en Nouvelle-Aquitaine,
      sous forme de prêts d'honneur jusqu'à 100K€ et/ou de participation au capital
      jusqu'à 3M€.</p>
  <h2><b>Notre équipe</b></h2>
  <p>L'équipe est répartie entre Bordeaux, Poitiers et Limoges.</p>
  <p>Vous pouvez consulter nos profils sur <a href="https://www.linkedin.com/company/2795653/"><em>LinkedIn</em></a>.
        Nous sommes également sur <a href="http://twitter.com/AquitiGestion"><em>Twitter</em></a>.
        N'hésitez pas à nous ajouter et à nous suivre. Nous communiquons principalement
        par <em>email</em>.</p>
    <h2><b>Reporting</b></h2>
    <p>Il est essentiel d'informer vos investisseurs régulièrement sur votre activité.</p>
    <p>Nous vous remercions de bien vouloir nous mettre en copie de vos rapports d'activités.
        Les meilleures entreprises nous les communiquent une fois par mois. Nous vous
        donnons quelques conseils dans <a href="http://www.aquiti.fr/6-indicateurs/">cet article</a> et vous pouvez télécharger ici <a href="https://cl.ly/2g3q2I3A0l1b">un exemple de format</a>.</p>
    <h2><b>Enquête d'activités annuelle</b></h2>
    <p>En plus du reporting mensuel, nous vous solliciterons 1 fois par an pour vous demander
        quelques données économiques. Notre objectif est que cela reste le plus simple
        et le moins chronophage possibles pour vous.</p>
    <p><b>Les pages suivantes ont pour objectif de vous partager les principes qui nous semblent essentiels pour la réussite de votre entreprise. Pour aller plus loin, sur des sujets plus spécifiques, nous vous invitons à explorer les ressources disponibles sur </b><b><i><a href="http://www.witty.vc">witty.vc</a>.</i></b>
    </p>
  </div>

<div id="onboarding_text_2">
  <h1>Ce que nous attendons des entrepreneur(e)s</h1>
  <p>Nous savons que l'entrepreneuriat est un challenge quotidien.</p>
  <p>Nous sommes à vos côtés pour vous donner les moyens, les ressources et l'expertise
      nécessaire pour réussir votre entreprise.</p>
  <h2>Quelque soit votre expérience, nous tenons à vous rappeler <b>les éléments qui nous semblent importants pour votre réussite</b> :</h2>
  <ul>
      <li><b>Construisez la meilleure équipe</b>. C'est essentiel. Recrutez des personnes
          partageant votre engagement et surpassez-vous.</li>
      <li><b>Développez votre capacité d'apprentissage</b>. Apprenez tous les jours de
          vos erreurs pour prendre de meilleurs décisions.</li>
      <li><b>Trouvez l'équilibre</b> entre ambition et humilité, entre capacité d'écoute
          et détermination.</li>
      <li><b>Restez focus</b>. Votre capacité d'exécution est essentielle.</li>
      <li><b>Accélérez</b>. Vos décisions doivent avoir pour principal objectif de développer
          et de créer davantage de valeur pour votre entreprise.</li>
  </ul>
  <p>Nous sommes ravis de participer au financement de votre entreprise, nous souhaitons
      votre réussite, mais nous sommes humains avant tout. Nous ne pouvons travailler
      efficacement que si et seulement si vous nous communiquez régulièrement des informations
      claires, honnêtes et pertinentes.</p>
  <p>Nous ne sommes pas des investisseurs à court-terme, nous ne finançons pas votre trésorerie
      et nous ne pouvons pas trouver de solutions si vous ne nous partagez pas d'informations
      régulièrement.</p>
  <h2>Par conséquent, <b>ce que nous attendons de vous</b> :</h2>
  <ul>
      <li><b>Communiquez régulièrement</b>, au moins 1 fois par mois. Que ce soit des réussites
          ou des difficultés, restez honnêtes et transparents.</li>
      <li><b>Soyez succints</b>, faites simple et efficace. Un email avec quelques indicateurs
          clés nous suffit.</li>
      <li><b>L'argent est le nerf de la guerre</b>. Dites-nous combien vous dépensez tous
          les mois et combien vous disposez sur votre compte bancaire. Ne nous dites
          pas que tout se passe bien si vous êtes en difficultés le mois suivant.</li>
  </ul>
  <h3><strong>A vous de jouer !</strong></h3>
</div>

<div id="onboarding_text_3">
  <h1>Ce que vous pouvez attendre de nous</h1>
  <p>Nous attendons d'être régulièrement informés de vos activités et vous pouvez compter
      sur notre soutien et notre engagement pour vous apporter notre expérience, nos
      conseils et notre écosystème d'experts.</p>
  <h2><b>Par conséquent, vous pouvez attendre de nous</b>:</h2>
  <ul>
      <li><b>Une proximité</b> et une disponibilité pour répondre simplement, rapidement
          et de manière pertinente à vos besoins. Notre <em>focus</em> est de vous
          apporter un maximum de valeur ajoutée.</li>
      <li><b>L'expérience</b> de notre relation avec les entrepreneurs et les acteurs de
          l'innovation en Nouvelle-Aquitaine et en France nous permet d'analyser et
          d'identifier les bonnes pratiques. Nous les partageons avec vous tous les
          mois.</li>
      <li><b>Des outils</b> pour vous aider à accélérer et à piloter votre croissance,
          comme des reportings, des pipes commerciaux, des <em>pitch deck</em>... Nous
          comptons également sur vous pour partager vos propres retours d'expérience
          aux autres entrepreneurs.</li>
      <li><b>Des experts en innovation </b>mobilisés pour répondre à des besoins particuliers:
          financements, gestion d'équipe, communication, innovation...</li>
  </ul>
  <p>Nous sommes engagés pour vous donner les moyens de réussir mais nous sommes humains
      avant tout. Il peut arriver que nous n'ayons pas la réponse ou la solution à
      votre demande. Comptez sur nous pour vous répondre <strong>honnêtement et en toute transparence</strong></p>
</div>

<div class="understood-button-block">
  <a class="btn btn-success" href="/">Ok, j'ai compris. Action !</a>
</div>

app/views/pages/_text_intro.html.erb
<p>Bonjour,</p>
<p>Je souhaite rencontrer cette personne:</p>
  <p><strong><%= @contact.title %>.</strong></p>
  <p><em><%= @contact.description %></em></p>
<p>Pour la raison : ........ </p>
<p>Pour rappel, notre activité :</p>
<ul>
  <li>Solution : ..........</li>
  <li>Marché visé : .....</li>
</ul>
<p><strong>Nos derniers indicateurs :</strong></p>
<ul>
  <li>Chiffre d’affaires mensuel : ......€</li>
  <li>Nombre de clients : ......#</li>
  <li>Taux de satisfaction : .....%</li>
</ul>
<p>Merci</p>
<p>Bonne journée</p>

app/views/pages/_text_report.html.erb
<p>Bonjour,</p>
<p><strong>Nos derniers indicateurs :</strong></p>
<ul>
  <li>Chiffre d’affaires mensuel : .......€</li>
  <li>Dépenses mensuelles : .......€</li>
  <li>Trésorerie disponible à date : .......€</li>
  <li>Nombre de clients : .......#</li>
  <li>Taux de conversion lead - client : ........%</li>
  <li>Taux de satisfaction client : .......%</li>
</ul>
<p><strong>Mes besoins :</strong></p>
  <em>Une nouvelle offre d’emploi?</em><br>
  <em>Une mise en relation avec un de nos experts?</em>
  <em>Un conseil particulier ?</em><br><br>

<p><strong>Quelques informations diverses :</strong></p>
  <em>Un nouveau cas client ? Une récente publication ? <br>
      Une interview ? Bonne nouvelle ou mauvaise nouvelle ; <br>
      Peu importe, nous sommes à votre écoute...</em><br><br>
<p>Merci,</p>
<p>Bonne journée</p>

app/views/pages/_unboarding_text_1.html.erb
<h1>
  <strong>Cher(e)s entrepreneur(e)s, ensemble nous démarrons notre
  collaboration, voici quelques recommandations.</strong>
</h1>

<h2 class="welcome">
  BIENVENUE
</h2>
<p>
  Nous vous remercions pour votre confiance et sommes ravis de participer au
  développement de votre entreprise.
</p>
<p>
  Vous recevrez prochainement vos identifiants pour accéder à notre plateforme
  et nous reviendrons vers vous dans quelques semaines pour vous présenter nos
  prochaines actions.
</p>

<h2>
  Avant propos
</h2>
<p>
  Pour démarrer, nous vous avons préparé ce guide avec pour objectif de vous
  partager quelques principes qui nous semblent essentiels pour la réussite de
  votre entreprise.
</p>
<p>
  D'abord, nous souhaitons rapidement nous présenter et partager quelques
  détails pratiques :
</p>

<h2>
  Nos métiers
</h2>
<p>
  Depuis 1998, notre mission est de participer au développement économique de
  la Nouvelle-Aquitaine en participant au financement des fonds propres des
  start-up innovantes et des PME de la Nouvelle-Aquitaine
</p>
<p>
  Nous investissons dans 2 à 3 entreprises tous les mois sous deux formes, en
  prêts d'honneur et/ou en prise de participation minoritaire au capital social
  des entreprises.
</p>
<p>
  En 2018, nos objectifs :
</p>
<ul>
  <li>30 projets d'innovation</li>
  <li>1 800 000 euros sous forme de prêts d'honneur</li>
</ul>

<h2>
  Notre équipe
</h2>
<p>
  Vous pouvez consulter notre expérience sur LinkedIn. Nous sommes basés à
  Bordeaux et travaillons beaucoup par email et par Skype. N'hésitez pas à nous
  suivre.
</p>

<h2>
  Tech Stack
</h2>
<p>
  -- Outlook, Word, Excel, Powerpoint, Keynote, Sketch, Skype, Wunderlist,
  Evernote, Solid, Buffer, Mailjet, WordPress, CloudApp, Spotify
</p>

<h2>
  One Step Forward
</h2>
<p>
  Vous bénéficierez prochainement d'un accès à notre plateforme pour utiliser
  nos outils et rencontrer le reste de la communauté.
</p>

<h2>
  Communication
</h2>
<p>
  Sauf contre-indication de votre part, nous ajoutons votre logo à notre liste
  d'entreprises soutenues, publierons un article de blog et le diffuserons
  auprès de notre communauté. Nous vous remercions de nous mentionner sur votre
  site internet.
</p>

<h2>
  Reporting
</h2>
<p>
  Il est essentiel d'informer vos financeurs régulièrement sur votre activité.
  Nous vous remercions de bien vouloir nous mettre en copie de vos rapports
  d'activités. Les meilleures entreprises nous les communiquent une fois par
  mois. Vous pouvez retrouver plus loin dans ce guide un exemple de format.
</p>

<h2>
  Enquête d'activités annuelle
</h2>
<p>
  En plus du reporting mensuel, nous vous solliciterons 1 fois par an pour vous
  demander quelques données économiques. Notre objectif est que cela reste le
  plus simple et le moins chronophage possibles pour vous.
</p>

<h2>
  Mises en relation
</h2>
<p>
  N'hésitez pas à nous mettre en relation avec d'autres entrepreneurs intéressés
  par notre programme, nous estimons votre opinion et les renseignerons en
  priorité.
</p>

<h2>
  Retours d'expérience
</h2>
<p>
  Un avis, une remarque ? Nous sommes à votre écoute.
</p>
<ul>
  <li>Ce que nous attendons des entrepreneurs</li>
  <li>Ce que les entrepreneurs peuvent attendre de nous</li>
  <li>Quels indicateurs pour suivre la performance de votre entreprise
    innovante ?</li>
</ul>

<p>
  <strong>Ces premières pages ont pour objectif de vous partager les principes
  qui nous semblent essentiels pour la réussite de votre entreprise. Pour aller
  plus loin, sur des sujets plus spécifiques, nous vous invitons à explorer les
  ressources disponibles sur <%= link_to "http://aquiti.herokuapp.com/",
    "http://aquiti.herokuapp.com/" %></strong>
</p>

app/views/pages/_unboarding_text_2.html.erb
<strong><h1>
  <strong>Ce que nous attendons des entrepreneurs</strong>
</h1>

<p>
  Nous investissons sous forme de prêts d'honneur dans des
  entrepreneur(e)s engagé(e)s dans des projets d'innovation à fort potentiel de
  développement, de création de valeur et d'emplois.
</p>
<p>
  Nous sommes ravis de participer au financement de votre entreprise et
  à présent, notre objectif est de vous donner les moyens d'accélérer votre
  développement, technique et commerciale.
</p>
<p>
  Par expérience, nous savons que l'entrepreneuriat est un challenge
  quotidien et pour cette raison, nous sommes à vos côtés pour vous donner les
  moyens, les ressources et l'expertise nécessaire pour réussir votre
  entreprise.
</p>
<p>
  Quelque soit votre expérience, nous tenons à vous rappeler les
  éléments qui nous semblent essentiels pour votre réussite :</p>
<ul>
  <li>
    <p>
      Construisez la meilleure équipe. C'est essentiel. Recrutez des
      personnes partageant votre engagement et surpassez-vous,Développez votre
      capacité d'apprentissage. Apprenez tous les jours de vos erreurs pour
      prendre de meilleurs décisions,Trouvez l'équilibre entre ambition et
      humilité, entre capacité d'écoute et détermination.Restez focus. Votre
      capacité d'exécution est essentielle.Accélérez. Vos décisions doivent avoir
      pour principal objectif de développer et de créer davantage de valeur pour
      votre entreprise.
    </p>
  </li>
</ul>

<p>
  Nous sommes ravis de participer au financement de votre entreprise,
  nous souhaitons votre réussite, mais nous sommes humains avant tout. Nous ne
  pouvons travailler efficacement ensemble que si et seulement si vous nous
  communiquez régulièrement des informations claires, honnêtes et
  pertinentes.
</p>
<p>
  Nous ne sommes pas des financeurs à court-terme, nous ne finançons pas
   votre trésorerie et nous ne pouvons pas trouver de solutions si vous ne nous
   partagez aucune information pendant des mois. Ensemble, nous avons un
   engagement de confidentialité pour travailler en toute transparence et en
   toute confiance.
</p>
<p>
  En conséquence, ce que nous attendons de vous :
</p>
<ul>
  <li>
    <p>
      Communiquez régulièrement, au moins 1 fois par mois. Que ce soit
      des réussites ou des difficultés, restez honnêtes et transparents.Soyez
      succints, faites simple et efficace. Un email avec quelques indicateurs
      clés nous suffit.L'argent est le nerf de la guerre. Dites-nous combien
      vous dépensez tous les mois et combien vous disposez sur votre compte
      bancaire. Ne nous dites pas que tout se passe bien et être en difficultés
      un mois plus tard.
    </p>
  </li>
</ul>

<p>
  A vous de jouer !
</p></strong>

app/views/pages/_unboarding_text_3.html.erb
<strong><h1>
  <strong>Ce que les entrepreneurs peuvent attendre de nous</strong>
</h1>

<p>
  Une fois le versement des fonds, vous retournez à votre activité et
  nous reprenons nos demandes de financement. Pourtant, nous sommes à présent liés.
  Nous attendons d'être régulièrement informés de vos activités et vous pouvez
  compter sur notre soutien et notre engagement pour vous apporter notre
  expérience, nos conseils et notre communauté d'experts.
</p>
<p>
  Ce que vous pouvez attendre de nous :
</p>
<ul>
  <li>
    <p>
      Une proximité et une disponibilité pour répondre simplement,
      rapidement et de manière pertinente à vos besoins. Notre focus est de vous
      apporter de la valeur ajoutée.L'expérience de notre relation avec les
      entrepreneurs et les acteurs de l'innovation en Nouvelle-Aquitaine et en
      France nous permet d'analyser et d'identifier les bonnes pratiques. Nous
      les partageons avec vous tous les mois.Des experts en innovation mobilisés
      pour répondre à des besoins particuliers: financements, structuration,
      communication, innovation.Des outils pour vous aider à accélérer et à
      piloter votre croissance, comme des reportings, des pipes commerciaux,
      des pitch deck... Nous comptons également sur vous pour partager vos
      propres retours d'expérience aux autres entrepreneurs.
    </p>
  </li>
</ul>

<p>
  Nous sommes engagés pour vous donner les moyens de réussir mais nous
  sommes humains avant tout. Il peut arriver que nous n'ayons pas la réponse ou
  la solution à votre demande. Nous vous le dirons en toute transparence. Nous
  devons tous apprendre à dire non et à accepter lorsqu'il le faut.
</p></strong>

app/views/pages/_unboarding_text_4.html.erb
<strong><h1><strong>
  Quels indicateurs pour suivre la performance de votre entreprise innovante ?
</strong></h1>

<p>
  En tant qu'entrepreneur(e), il est essentiel de mesurer et de
  maîtriser vos indicateurs clés, pour connaître vos performances, anticiper
  vos besoins et convaincre vos potentiels investisseurs.
</p>
<p>
  Alors, quel tableau de bord construire et avec quelles données ?
</p>
<p>
  Selon votre activité et vos problématiques, il existe de nombreux
  indicateurs différents.
</p>
<p>
  <%= link_to 'https://a16z.com/2015/08/21/16-metrics/',
  'https://a16z.com/2015/08/21/16-metrics/' %>
</p>
<p>
  Pour commencer, nous vous proposons les données qui nous semblent
  essentiels, ainsi que le tableau de bord “kit de démarrage” à télécharger et
  à mettre à jour régulièrement.
</p>
<p>
  Trois catégories d’indicateurs
</p>
<p>
  Nous avons structurés le tableau de bord autour de trois catégories :
</p>
<ul>
  <li>
    Les indicateurs financiers. C'est le nerf de la guerre et en tant
    que dirigeant d'entreprise, vous devez parfaitement maîtriser ces chiffres
    par anticiper vos besoins ;L'avancement commercial, pour savoir si vous
    parvenez à convaincre vos prospects efficacement.La satisfaction client,
    pour savoir si votre produit répond aux besoins de vos clients et s'ils
    sont satisfaits.
  </li>
</ul>
<p>
  Ci-dessous, la description des indicateurs pour chaque catégorie :
</p>
<p>
  Indicateurs financiers
</p>
<ul>
  <li>
    Chiffre d'affaires mensuel
  </li>
</ul>
<p>
  Votre chiffre d'affaires mensuel permet de mesurer votre volume d'activités
  sur 1 mois. Si vous ne générez pas encore de revenus, identifiez d'autres
  données liées à votre activité. Pour un projet numérique, cela peut être le
  nombre d'utilisateurs actifs mensuels par exemple.
</p>
<ul>
  <li>
    Dépenses mensuelles
  </li>
</ul>
<p>
  Il est essentiel de connaître le montant de vos dépenses mensuelles. En
  tant que dirigeant d'entreprise, votre objectif est de maintenir un niveau de
  dépenses raisonnable. Si vous observez une augmentation significative
  inexplicable, demandez-vous quels sont les leviers actionnables pour diminuer
  vos dépenses. Cette donnée est importante et est à mettre en perspective avec
  votre chiffre d'affaires mensuel pour savoir si vous gagnez de l'argent ou si
  vous en perdez, et avec votre trésorerie disponible pour anticiper un
  éventuel besoin financier.
</p>
<ul>
  <li>
    Trésorerie disponible
  </li>
</ul>
<p>
  En tant que dirigeant d'entreprise, vous devez également savoir précisément
  de combien vous disposez sur votre compte bancaire. N'oubliez pas qu'il est
  plus simple de trouver des financements publiques ou privés lorsque vous n'en
  avez pas besoin. D'abord parce que les processus sont longs, ensuite parce
  que cela démontre que vous savez gérer votre entreprise et enfin parce que
  cela vous met dans les meilleures conditions pour négocier.
</p>
<p>
  Avancement commercial
</p>
<ul>
  <li>
    Nombre de clients payants
  </li>
</ul>
<p>
  Cette donnée est à mettre en perspective avec le nombre de clients
  enregistrés sur la période suivante pour évaluer la performance de vos
  actions commerciales.
</p>
<ul>
  <li>
    Taux de transformation client
  </li>
</ul>
<p>
  L'objectif est de savoir si vos techniques d'acquisition clients fonctionnent
  et si vos actions sont efficaces pour convertir des prospects en clients.
</p>
<p>
  Pour obtenir cette donnée, il suffit de calculer le pourcentage entre le
  nombre de prospects contactés et le nombre de nouveaux clients signés.
</p>
<p>
  Satisfaction client
  </p>
<ul>
  <li>
    Net Promoter Score
  </li>
</ul>
<p>
  Le Net Promoter Score (NPS) vous permet de savoir si votre produit ou
  service répond aux attentes de vos utilisateurs en quantifiant leur niveau
  de satisfaction.
</p>
<p>
  Cet indicateur permet de mesurer la satisfaction et le degré de fidélisation
  de vos clients. Il permet d’identifier vos clients promoteurs, détracteurs et
  passifs et ainsi d’orienter vos actions marketing vers le bon groupe de
  clients au bon moment.
</p>
<p>
  Les indicateurs métiers
</p>
<p>
  Au-delà de tous ces indicateurs très génériques, il nous semble indispensable
  que vous mettiez en place très tôt des indicateurs de performance spécifiques
  à votre activité. C’est à vous de les définir, de suivre leur évolution, de
  les comparer aux standards du secteur et de fixer des objectifs à atteindre
  pour piloter votre activité et motiver vos équipes. 3 ou 4 indicateurs
  suffisent généralement mais il faut sélectionner les plus pertinents. Pour
  une start-up numérique, il y a l’embarras du choix : nombre de visiteurs
  uniques, taux de rebond, coût d’acquisition client, taux de trafic naturel vs
  payant, taux de retour…. Pour les logiciels SaaS aussi même si on suit
  généralement le nombre d’utilisateurs, le MRR (Monthly Recurring Revenue) et
  le taux de churn. Pour les sociétés industrielles, on peut par exemple
  s’intéresser aux taux d’occupation de la ligne, taux de rebut, taux de
  rotation des stocks ainsi bien sûr que la marge brute.
</p>
<p>
  Pour finir, comment utiliser ce tableau de bord "kit de démarrage", pour qui
  et à quelle fréquence ?
</p>
<p>
  Le suivi de vos performances par des données chiffrées est essentiel pour
  valider vos hypothèses, comprendre vos réussites, analyser vos échecs et
  prendre les décisions et les actions pertinentes.
</p>
<p>
  Ce tableau de bord peut s'adresser à trois profils différents :
</p>
<ul>
  <li>
    Pour vous d'abord, pour vous permettre de prendre du recul sur votre
    activité quotidienne. Pour votre équipe également, pour être transparent
    sur la performance de l'entreprise. Pour vos investisseurs et vos
    financeurs enfin, pour gagner leur confiance, valoriser vos succès et
    anticiper vos difficultés.
  </li>
</ul>
<p>
  Nous vous encourageons à suivre ces indicateurs dès le début de votre
  activité, sur un rythme mensuel. Créez une action mensuelle dans votre
  gestionnaire ou utilisez ce script pour vous envoyer un rappel tous les mois.
</p>
<p>
  <%= link_to 'https://zapier.com/app/editor/template/1926',
  'https://zapier.com/app/editor/template/1926' %>
</p>
<p>
  Pour finir, quelques conseils complémentaires :
</p>
<ul>
  <li>
    Comparez vos données dans la duréeÀ l’instant t, il peut être difficile
    de comprendre la signification d'une donnée. Les chiffres sont intéressants
    de façon dynamiques, en comparaison à d'autres périodes. En démarrant
    maintenant et en mettant à jour régulièrement et sérieusement ce tableau de
    bord, vous mesurez rapidement la valeur ajoutée.Essayez d’avoir une vision
    “d’avant” Si vous ne partez pas de zéro, nous vous invitons à inclure dans
    votre tableau de bord l’historique de votre activité. Si possible,
    remontez sur 12 mois, au minimum 6 mois, pour observer, comparer et
    comprendre les évolutions, pour prendre plus rapidement les decisions et
    les actions nécessaires au développement de votre entreprise.Fixez-vous des
    objectifsFixez-vous des objectifs clairs et chiffrés, en réfléchissant aux
    moyens que vous allez mettre en oeuvre pour y parvenir.
  </li>
</ul>
<p>
  A présent, à vous de jouer !
</p>
<p>
  N’hésitez pas à partager cet article autour de vous s’il vous a été utile
  (nous apprécions beaucoup les partages, cela nous encourage à partager encore
  plus avec vous !) et surtout à télécharger d’urgence le modèle de tableau de
  bord !
</p></strong>

app/views/pages/ask_intro.html.erb
<div class="container">
  <div class="row larger-borders">
    <div class="col-xs-12">
      <div class="form-model">
        <h1 class="text-center report-title"><%= "#{t('.intro')} #{@contact.title}" %></h1>
        <p class="text-center" id="italic-under-title">
          <%= t('.email') %>
        </p>
        <%= render 'shared/mail_form', text: 'text_intro'%>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<p>Hi, this is the unboarding page ! :D</p>

app/views/pages/onboarding.html.erb
<% content_for :title, "- How does this work?" %>

<ul class="button-tags-onboarding-container smaller-tags-container text-center
  nav nav-tabs" id="navbar-scrollspy" role="tablist" data-target="#onboarding-scrollspied">
  <li role="tablist" class="active">
    <%= link_to '#onboarding_text_1', 'aria-controls': "onboarding_text_1",
    'arial-label': "onboarding_text_1", class: "green-credits nav-link" do %>
      Bienvenue
    <% end %>
  </li>
  <li role="tablist">
    <%= link_to '#onboarding_text_2', 'aria-controls': "onboarding_text_2",
    'arial-label': "onboarding_text_2", class: "green-credits nav-link" do %>
      Nos attentes
    <% end %>
  </li>
  <li role="tablist">
    <%= link_to '#onboarding_text_3', 'aria-controls': "onboarding_text_3",
    'arial-label': "onboarding_text_3" , class: "green-credits nav-link" do %>
      Nos actions
    <% end %>
  </li>
  <%= render 'shared/credits' %>
</ul>

<div class="tab-content cards-container onboarding-container summernote"
  id="onboarding-scrollspied" data-spy="scroll" data-offset="20">

  <%= render partial: "onboarding_text" %>
</div>

<%= form_tag onboarding_path, method: :post, class: "edit-wysiwyg" do %>
  <%= buttons_edit_onboarding(current_user) %>
  <%= hidden_field_tag(:onboarding_page) %>
  <%= submit_tag 'Save', class: 'btn btn-primary hidden', id: "save" %>
<% end %>

app/views/pages/send_report.html.erb
<div class="container larger-borders">
  <div class="row">
    <div class="col-xs-12">
    <div class="form-model">

        <h1 class="text-center report-title"><%= t('.your-report') %></h1>
        <p class="text-center" id="italic-under-title">
          <%= t('.send-email') %></p>
        <%= render 'shared/mail_form', text: 'text_report' %>

    </div>
  </div>
</div>